version: '3.8'
services:
  db:
    container_name: expenses-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - expenses-network
  fms:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - expenses-network
volumes:
  db:
    driver: local
networks:
  expenses-network: